wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.5
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726230476
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.12.5
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
exp:
  desc: null
  value: mnist_threshold_1
log_dir:
  desc: null
  value: ./logs
data_dir:
  desc: null
  value: /mnisttt
threshold:
  desc: null
  value: 1
train_json:
  desc: null
  value: ./instances_train.json
val_json:
  desc: null
  value: ./instances_val.json
max_length:
  desc: null
  value: 128
precision:
  desc: null
  value: 8
element_order:
  desc: null
  value: raster
attribute_order:
  desc: null
  value: cxywh
seed:
  desc: null
  value: 42
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 4.5e-06
n_layer:
  desc: null
  value: 6
n_embd:
  desc: null
  value: 512
n_head:
  desc: null
  value: 8
lr_decay:
  desc: null
  value: false
warmup_iters:
  desc: null
  value: 0
final_iters:
  desc: null
  value: 0
sample_every:
  desc: null
  value: 1
